console.log('process.env', process.argv)

const obj = {
    TERM_PROGRAM: 'vscode',
    NODE: '/usr/local/bin/node',
    INIT_CWD: '/Users/xizhou/workSpace/my_github/node/07_node服务器koa',
    TERM: 'xterm-256color',
    SHELL: '/bin/zsh',
    npm_config_metrics_registry: 'https://registry.npmjs.org/',
    TMPDIR: '/var/folders/1t/ssgg5tw523zgqt67b57b9jnw0000gn/T/',
    npm_config_global_prefix: '/usr/local',
    TERM_PROGRAM_VERSION: '1.83.1',
    ZDOTDIR: '/Users/xizhou',
    ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
    MallocNanoZone: '0',
    COLOR: '1',
    npm_config_noproxy: '',
    npm_config_local_prefix: '/Users/xizhou/workSpace/my_github/node/07_node服务器koa',
    USER: 'xizhou',
    COMMAND_MODE: 'unix2003',
    npm_config_globalconfig: '/usr/local/etc/npmrc',
    SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.jPqUY8dydQ/Listeners',
    __CF_USER_TEXT_ENCODING: '0x1F5:0x19:0x34',
    npm_execpath: '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
    PATH: '/Users/xizhou/workSpace/my_github/node/07_node服务器koa/node_modules/.bin:/Users/xizhou/workSpace/my_github/node/node_modules/.bin:/Users/xizhou/workSpace/my_github/node_modules/.bin:/Users/xizhou/workSpace/node_modules/.bin:/Users/xizhou/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/mysql/bin:/usr/local/mysql/bin',
    npm_package_json: '/Users/xizhou/workSpace/my_github/node/07_node服务器koa/package.json',
    _: '/usr/local/bin/node',
    LaunchInstanceID: 'A9C3A413-673C-475A-9790-CBACDFE5C9DC',
    npm_config_userconfig: '/Users/xizhou/.npmrc',
    npm_config_init_module: '/Users/xizhou/.npm-init.js',
    USER_ZDOTDIR: '/Users/xizhou',
    __CFBundleIdentifier: 'com.microsoft.VSCode',
    npm_command: 'run-script',
    PWD: '/Users/xizhou/workSpace/my_github/node/07_node服务器koa',
    npm_lifecycle_event: 'test',
    EDITOR: 'vi',
    npm_package_name: 'learn_koa',
    LANG: 'en_US.UTF-8',
    'npm_config_https://registry.npm.taobao.org': '',
    VSCODE_GIT_ASKPASS_EXTRA_ARGS: '--ms-enable-electron-run-as-node',
    XPC_FLAGS: '0x0',
    npm_config_node_gyp: '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
    npm_package_version: '1.0.0',
    XPC_SERVICE_NAME: '0',
    VSCODE_INJECTION: '1',
    SHLVL: '2',
    HOME: '/Users/xizhou',
    VSCODE_GIT_ASKPASS_MAIN: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js',
    npm_config_cache: '/Users/xizhou/.npm',
    LOGNAME: 'xizhou',
    npm_lifecycle_script: 'node 11_自由练习.js --params=123',
    VSCODE_GIT_IPC_HANDLE: '/var/folders/1t/ssgg5tw523zgqt67b57b9jnw0000gn/T/vscode-git-bdccdaf951.sock',
    npm_config_user_agent: 'npm/8.19.4 node/v16.20.0 darwin arm64 workspaces/false',
    VSCODE_GIT_ASKPASS_NODE: '/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)',
    GIT_ASKPASS: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh',
    SECURITYSESSIONID: '186a3',
    npm_node_execpath: '/usr/local/bin/node',
    npm_config_prefix: '/usr/local',
    COLORTERM: 'truecolor'
  }